resolver: lts-14.12
packages:
  - .

extra-deps:
  - rope-utf16-splay-0.3.1.0
  - github: alanz/haskell-lsp
    commit: dd551b97119ea5fbb0bd1ed4ee16686a5d13b04f
    subdirs:
      - .
      - haskell-lsp-types
